# -*- coding: utf-8 -*-
"""Bajaj_Auto

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/181Y8mAd_u2jqNAEIupkgnhrWw8rI68m6
"""

pip install quandl

import quandl
import numpy as np

quandl.ApiConfig.api_key = 'FZCdiqtsRgoffcyx2XqB'

df = quandl.get("XNSE/BAJAJ_AUTO")
print(df.head())

df.info()

x = df.drop("Adjustment Factor",axis=1)
y = x.drop("Adjustment Type",axis=1)
print(y)

y = y[['Close']]
print(y.head())

# Variable for prediction for future days
forecast = 10
y['Prediction'] = y[['Close']].shift(-forecast)

print(y.tail())

w = y.drop(['Prediction'],1)
w = w[:-forecast]
print(w)

q=y['Prediction']
q=q[:-forecast]
print(q)

from sklearn.svm import SVR
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(w,q,test_size =0.20)

svr_rbf = SVR(kernel='rbf',C=1e3)
svr_rbf.fit(x_train,y_train)

svr_out = svr_rbf.score(x_test,y_test)
print (svr_out)

x_forecast = y.drop(['Prediction'],1)[-forecast:]
print(x_forecast)

svr_prediction = svr_rbf.predict(x_forecast)
print(svr_prediction)

import matplotlib.pyplot as plt

z = y['2018-11-30':]

plt.figure(figsize=(16,8))
plt.title('Bajaj Auto')
plt.xlabel('Days')
plt.ylabel('Close Price INR')
plt.plot(y['Close'])
plt.show()

predict = svr_prediction
valid = y[w.shape[0]:]
valid['Predict'] = predict

plt.figure(figsize=(16,8))
plt.title('Bajaj Auto')
plt.xlabel('Days')
plt.ylabel('Close Price INR')
plt.plot(z['Close'])
plt.plot(valid[['Close','Predict']])
plt.legend(['Orig','Val','Pred'])
plt.show()